apiVersion: v1
kind: Pod
metadata:
  name: pod-ubi-example
  labels:
    app: ubi-example
spec:
  containers:
    - command: ["/bin/sh", "-c"]
      args: 
      - rm -vf home/* 
      volumeMounts:
        - mountPath: /home
          name: existent-pvc 
      name: ubi8-image 
      image: ubi8 
  volumes:
    - name: existent-pvc
      persistentVolumeClaim:
        claimName: pvc-httpd-example 
