apiVersion: v1
kind: Pod
metadata:
  name: rsync-node-pod
  namespace: jobs 
spec:
  containers:
  - command:
    - /bin/sh
    image: registry.redhat.io/rhmtc/openshift-migration-rsync-transfer-rhel8:v1.7.13-3
    imagePullPolicy: Always
    name: container-00
    resources: {}
    securityContext:
      privileged: true
      runAsUser: 0
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /home
      name: volume-pvc 
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 5
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
    - name: volume-pvc
      persistentVolumeClaim:
        claimName: pvc-httpd-example
