apiVersion: batch/v1
kind: Job
metadata:
  name: httpd-job 
  labels:
    app: httpd-example
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 500 
  backoffLimit: 6
  template: 
    metadata:
      name: httpd-job 
    spec:
      containers:
        - command: ["sleep", "220"]
          name: ubi8-image 
          image: ubi8 
      restartPolicy: OnFailure
