apiVersion: batch/v1
kind: Job
metadata:
  name: httpd-job 
  labels:
    app: httpd-example
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 500 
  backoffLimit: 6
  template: 
    metadata:
      name: httpd-job 
    spec:
      containers:
      - name: httpd-jobpod 
        image: registry.access.redhat.com/ubi8/ubi:8.4-209 
        command:
          - /bin/bash
          - sleep
          - "20"
      restartPolicy: OnFailure
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: existent-pvc 
    volumes:
      - name: existent-pvc
        persistentVolumeClaim:
          claimName: pvc-httpd-example 
