apiVersion: v1
kind: Pod
metadata:
  name: job-pod-httpd-example 
  labels:
    app: httpd-example
spec:
  containers:
    - name: frontend
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: existent-pvc 
  volumes:
    - name: existent-pvc
      persistentVolumeClaim:
        claimName: pvc-httpd-example 
