apiVersion: v1
kind: Pod
metadata:
  name: pod-ubi-example
  labels:
    app: ubi-example
spec:
  containers:
    - command: ["sleep", "40"]
      name: ubi8-image 
      image: ubi8 
      volumeMounts:
        - mountPath: /home
          name: existent-pvc 
  volumes:
    - name: existent-pvc
      persistentVolumeClaim:
        claimName: pvc-httpd-example 
