apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-httpd-example
spec:
  accessModes:
  - ReadWriteOnce 
  volumeMode: Block
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi 
